-- Este script borra todos los registros de la base de datos
-- SERVICIOSWEB_MAIN y SERVICIOSWEB_PAGOS
-- Utilize DATABASE_HANDLER para recobrar los registros quemados.

USE SERVICIOSWEB_MAIN;
GO

DELETE FROM USUARIO;

DELETE FROM ADMIN;

DELETE FROM CONSECUTIVO;

DELETE FROM GENEROS_PELICULAS;

DELETE FROM GENEROS_MUSICA;

DELETE FROM CATEGORIAS_LIBROS;

DELETE FROM PELICULA;

DELETE FROM MUSICA;

DELETE FROM LIBRO;

DELETE FROM TRANSACCION;

DELETE FROM BITACORA;

DELETE FROM PARAMETROS;

DELETE FROM DESCARGAS;

DELETE FROM ERROR;

USE SERVICIOSWEB_PAGOS;
GO

DELETE FROM TARJETA;

DELETE FROM EASYPAY;